### ISSUE TITLE
Import from Zelle not working properly

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#10]
### Description:

There are a few issues in this scenario, when Zelle was used before activating Neve.

1. The notice about migrating Zelle content to Neve doesn't appear unless the **Templates Patterns Collection** plugin is already installed, before activating Neve. If the plugin is installed from the notice available in Dashboard -> Neve Options, Starter sites tab, this option isn't available anymore.

2. When the notice is available, there is a missing screenshot.
![missing-zelle-screenshot](https://user-images.githubusercontent.com/26867648/92001794-cf069f00-ed47-11ea-8ae5-0cb9c9fbff02.png)

The error states that the image should be available in 

> /wp-content/themes/neve/vendor/codeinwp/themeisle-onboarding/migration/zelle/zelle.png

3. The import doesn't work.

![migration-from-zelle-failed](https://user-images.githubusercontent.com/26867648/92002176-3ae90780-ed48-11ea-9c03-a3682ff2d6e8.png)

### Reference:

Ticket: https://secure.helpscout.net/conversation/1270036242/243303/

### Technical info
* WordPress version: 5.5.1
* Theme version: 2.7.7
* Templates Patterns Collection: 1.0.9

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/1287910170/245979?folderId=212385

**Comment by rodica-andronache** [comment]
This is still happening after the update
`The notice about migrating Zelle content to Neve doesn't appear unless the Templates Patterns Collection plugin is already installed, before activating Neve. If the plugin is installed from the notice available in Dashboard -> Neve Options, Starter sites tab, this option isn't available anymore.`

Also, there's a small space here
![download](https://user-images.githubusercontent.com/3266155/93782148-e643f880-fc32-11ea-9621-83c182fd467d.png)

**Comment by abaicus** [comment]
@rodica-andronache I sent in a PR to fix this issue [on neve](https://github.com/Codeinwp/neve/pull/2139).

Also for the space below the image I sent in a dedicated fix [here](https://github.com/Codeinwp/templates-patterns-collection/pull/12).

Let me know if everything works fine :+1: :dancing_men:
