### ISSUE TITLE
Automate screenshot generation for Page Templates

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/templates-patterns-collection#100]
Automate screenshot generation for page templates using Thum.io.

**Comment by HardeepAsrani** [comment]
Should we still allow us (we who publish templates for users) to allow custom screenshot URL or should we also generate it using the API? @mghenciu @selul

**Comment by selul** [comment]
by default we could generate it using the API, but we should be able to replace them manually.

**Comment by HardeepAsrani** [comment]
Alright.

**Comment by mghenciu** [comment]
Something to keep in mind @HardeepAsrani:
- we take our screenshots at 1366x768 (which is the most common resolution). This way we make sure customers get what they see in the thumbnail
- I had some challenges with certain embedded elements (maps, video, soundcloud, etc), when using Screenshot tools, meaning that the embeds where not visible. So it may worth checking if Thum.io works as expected. I've tested [our funnel demo](https://demosites.io/sales-funnel/), which has a embedded video, and this is how it looks (first one on the left):
![image](https://user-images.githubusercontent.com/52494172/121317046-961cdb80-c912-11eb-945f-8b44652c8771.png)

I usually use [site-shot](https://www.site-shot.com/), which doesn't have any issues with embeds.

**Comment by HardeepAsrani** [comment]
An update 

@selul: I added all the things needed for this to API. So whatever version of TPC you are using, the screenshot will work without updating anything. Of course, it won't appear for older templates unless you update them.

This does make publishing slower. What would be the best way to perform screenshot updating asynchronously instead of waiting for it to finish before returning success?

Also, this doesn't work on localhost as we can't fetch those websites to generate a screenshot.

@irinelenache: Can you create new page templates on a test site and see if screenshots are generated for them? Try all editors.

@mghenciu: If you have a custom screenshot URL defined then screenshots won't be generated, FYI.

So yea, let me know feedback or any issues.

**Comment by HardeepAsrani** [comment]
And yes, I'll also add a "Regenerate" button to the TPC dashboard.

**Comment by selul** [comment]
> This does make publishing slower. What would be the best way to perform screenshot updating asynchronously instead of waiting for it to finish before returning success?

I think we can use schedule a background job to save the screenshot if the site validates ( is up, etc )

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] The header and footer being included in the screenshot is the expected behaviour?
- [ ] For **Elementor**, when i update the source page of a template, the screenshot isn't updated in **My library**

**Comment by mghenciu** [comment]
@irinelenache , have you also tested how the embedded components render in the Screenshot? for example g-maps, youtube embed.

I also remembered something related to Section height. May not be related to us, but it's something to keep in mind.
Basically if you set the height of a Section in Elementor to Fit to Screen, when I was using [site-shot](https://www.site-shot.com/) - the result was not good. I think it's because the screens are rendered in a VM or something like this, and it doesn't know what is Screen size of a VM.

This is how th[e page should look](https://supreme-gibbon.jurassic.ninja/elementor-30):
![Elementor #30 – Supreme Gibbon-2021-06-14](https://user-images.githubusercontent.com/52494172/121917357-b2b77a00-cd3d-11eb-987e-b960899127c3.png)


This is how it looks when using site-shot:
![Elementor #30 – Supreme Gibbon (1)](https://user-images.githubusercontent.com/52494172/121917416-c6fb7700-cd3d-11eb-9dce-8453d72befaf.png)

**Comment by HardeepAsrani** [comment]
@mghenciu Honestly, we can't do much about it. :)

**Comment by HardeepAsrani** [comment]
@irinelenache 

1. It takes a screenshot of the entire page so everything will appear.
2. Can you make sure the page is published and online? It won't work for local websites.

**Comment by HardeepAsrani** [comment]
@mghenciu You can always check it on jurassic ninja by the way. The stuff is already online so no need to pull and build.

**Comment by irinelenache** [comment]
@HardeepAsrani @mghenciu I checked the embeds and they worked fine.
I tried to test it again but now the feature doesn't work for me, in any page builder https://vertis.d.pr/E2yU0M

**Comment by HardeepAsrani** [comment]
@selul Any update on FlashAPI?

**Comment by selul** [comment]
I've shared the key with you on slack.

**Comment by selul** [comment]
@HardeepAsrani any update?

**Comment by HardeepAsrani** [comment]
Been busy with Otter stuff, will do this in a day or two.
