### ISSUE TITLE
Small UX improvements 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#101]
### Description:

I'll add here some quality of life features, I've found so far. I'll add more in the future if needed:

- [x] Double Scroll Bar on the Page Templates. Basically when you open a Import Modal, you have 2 scroll-bars on the right side:
![Screenshot 2021-06-07 at 12 46 45](https://user-images.githubusercontent.com/52494172/120995871-7f4d7c00-c78e-11eb-8f20-65a1b66519ca.png)

Maybe using something like `overflow-y: hidden` when a modal it's open, would work.
- [x] Add another Exit option for Import confirmation Modal. Can be ESC button or/and clicking outside.
From most of the modals used in TPC, you can exit using the ESC key or by clicking outside of the Modal, except this Import Confirmation modal. Maybe there's a reason for not having it here, but for accessibility we still need to a 'exit key' in this modal.
![image](https://user-images.githubusercontent.com/52494172/120997105-9d67ac00-c78f-11eb-94de-118746d8ad06.png)

- [x] Add back Icon on the Back to starter sites button, and rename the button to **Back to Starter Sites**
![Screenshot 2021-06-07 at 12 58 08](https://user-images.githubusercontent.com/52494172/120998029-5cbc6280-c790-11eb-9280-3e0b1e05e2a3.png)

- [x] Fix spacing/punctuation on the No results view
![Screenshot 2021-06-07 at 13 04 25](https://user-images.githubusercontent.com/52494172/120998712-03086800-c791-11eb-88fd-83d5bac5f28a.png)

- [x] When loading a page like /themes.php?page=tiob-starter-sites#pageTemplates the loading icon is not present being added at the bottom of the page. Also, I would use a skeleton loading as we did on starter sites by @abaicus which is nicer.

**Comment by selul** [comment]
I would also add this: 

- [ ] when loading a page like `/themes.php?page=tiob-starter-sites#pageTemplates` the loading icon is not present being added at the bottom of the page. Also, I would use a skeleton loading as we did on starter sites by @abaicus which is nicer.

**Comment by preda-bogdan** [comment]
The loading skeleton is not being used on the starter site section as it is not required since there is no fetching being done on that page anymore. 

I've repurposed the Loading component for the "Page Templates" and "My Library" section.

![image](https://user-images.githubusercontent.com/23024731/124911932-01cb9480-dff6-11eb-8bb6-436f2941c0ef.png)

![image](https://user-images.githubusercontent.com/23024731/124911961-098b3900-dff6-11eb-928c-d80d8721255a.png)
