### ISSUE TITLE
Exclude build files from GIT

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/templates-patterns-collection#104]
### Description:
Right now we have the build files included inside the repository.
This can create issues with PRs and also it should not be required to keep this. 
We should exclude those and make sure all build files are created with GitHub Actions on release.

This would keep the repository cleaner and improve workflow.

Is there a reason for having them as part of the repository? Is there a requirement that I'm missing?

**Comment by selul** [comment]
a list of files that we need to remove from tacking are: 

1.  Build JS files
2. Generated CSS Files
3. Pot file
