### ISSUE TITLE
Page Templates - tab not loading on refresh/back button

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#109]
### Description:

If an user goes to the Page Templates tab (under Appearance -> Neve Options > Starter Sites), and refreshed the page, the page is not loading anymore:

### How to reproduce:

1. Create a clean instance with Neve and TPC
2. Go to Page Templates tab (under Appearance -> Neve Options > Starter Sites)
3. Refresh the page (or just go to another page, and Go Back to Page Templates tab)
4. The page should not load properly

### Expected behaviour:
The page should load

### Current behaviour:
After refresh, the page isn't loading
### Reference:

https://www.loom.com/share/67fb2f55ed9e4d72a4b64853ae2602f4

### Technical info
* WordPress version: 5.7.2
* Theme version: 2.11.6
* TPC: 1.1.14

**Comment by preda-bogdan** [comment]
Opened a PR for this, the issue was caused by a block of code that was trying to set the Navigation select state for items that might not be there. Should be solved now.

**Comment by mghenciu** [comment]
Tested, and yes, the refresh on the Pate Templates tab **works as expected now**.
Thanks!
