### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/templates-patterns-collection#126]
### Description:
Client reported that there are strings from JS files that can't be translated.

For example, the description can be translated (the one above all the starter sites) but action buttons (Import, Preview, View Pages) also the names of starter sites can't be translated:
![image](https://user-images.githubusercontent.com/36594177/139907312-590584e3-1bd9-4d2f-9168-0d8ebd3e04c5.png)

I've tried myself and can confirm that they can't be translated (used Poedit to generate files).

The difference I see about how the translatable string is added compared to those that can't be translated is that translatable (description) is coming from PHP file and only has reference to it in JS file:
![image](https://user-images.githubusercontent.com/36594177/139908255-435771ed-02ee-4a0d-86ca-b400a0adec44.png)
![image](https://user-images.githubusercontent.com/36594177/139908303-ad6bcf1d-07a4-4faa-9d68-ebeb0c8ca26e.png)

While those that can't be translated are added directly in JS files:
![image](https://user-images.githubusercontent.com/36594177/139908425-88e864f4-e5d5-4c12-8ebd-2797516eb8d1.png)

### How to reproduce:
1. Activate Neve theme + Templates Pattern Collection plugin to import starter sites.
2. Use Poedit to generate .po and .po files with translations for Import, Preview, View Pages strings to be translated. Also, try to translate the names of the themes.
3. Check if translations appeared.

### Expected behaviour:
All strings should be translatable.

### Current behaviour:
Some strings are not translatable.

### Reference:
Reported here - https://secure.helpscout.net/conversation/1682943936/297795
File with translations is also provided in the ticket if needed for testing.

### Technical info
* WordPress version: 5.8.1
* Theme version: 3.0.10
* Template pattern collection version: 1.1.18

**Comment by cristian-ungureanu** [comment]
@vytisbulkevicius does `Import, Preview, View Pages` strings appear in the `.pot` file?

**Comment by vytisbulkevicius** [comment]
@cristian-ungureanu,

Yes, all 3 are in the .pot file of the plugin.
