### ISSUE TITLE
Remove upsell notice from gutenberg tab

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/templates-patterns-collection#134]
> The original description was that the notice would be shown only for tabs where there are exclusively pro sites: Codeinwp/neve-pro-addon#1739, however I see it as well on the gutenberg tab. Which is not ideal, especially at the first view.

**Comment by cristian-ungureanu** [comment]
@UVLabs please dont close the issues until their solution is in production.

**Comment by UVLabs** [comment]
> @UVLabs please dont close the issues until their solution is in production.

My bad 😅 i thought this was released already
