### ISSUE TITLE
Misaligned section in Lawyers Gutenberg site

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#141]
### Description:

After importing the Lawyers GB site, there is an alignment issue with the second section on the front page.

### Expected behaviour:

![Markup on 2022-03-28 at 23:25:21](https://user-images.githubusercontent.com/26867648/160481202-b457efbc-43c8-4a28-89dd-afd6c1202a6d.png)

### Current behaviour:

![Markup on 2022-03-28 at 23:25:03](https://user-images.githubusercontent.com/26867648/160481212-610c258d-9fd3-4801-bb89-d5048de4998c.png)

### Reference:

https://secure.helpscout.net/conversation/1826700148/315110/

### Technical info
* WordPress version: 5.9.2
* Theme version: 3.2.0
* Plugin version: 1.1.21

**Comment by mghenciu** [comment]
Fixed the issues yesterday, and after the sync-up today, everything looks good:
![image](https://user-images.githubusercontent.com/52494172/177006367-64f06fcb-3e07-425c-8cce-f877a40a337e.png)
