### ISSUE TITLE
Windows license shown in the image

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/templates-patterns-collection#159]
Hi there!

I was using one of the legacy starter sites ( Print Shop ), and I noticed that one of the photos has a notice that Windows is not activated:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/86592992/181465199-f613a02f-3d91-42aa-b099-ad288221f38e.png">

**Comment by preda-bogdan** [comment]
I think we can fix up and replace that image @mghenciu maybe check that we don't have similar images. What do you think?
I know it is a legacy import and that we don't actively support them but I think it's still better to not show that.

**Comment by mghenciu** [comment]
@AndreeaCristinaRadacina , could you please let me know what page is this exactly?
I found the green image, but can't see the one with the issue.

Theoretically we don't maintain the old sites, anymore.

**Comment by AndreeaCristinaRadacina** [comment]
@mghenciu it appears in the Media Library, and it's called img.2 - 
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/86592992/181906204-c770e365-a354-419a-b2d2-2264b29b478d.png">

If we don't maintain old sites anymore, it's okay.

**Comment by mghenciu** [comment]
> @mghenciu it appears in the Media Library, and it's called img.2 - <img alt="image" width="1612" src="https://user-images.githubusercontent.com/86592992/181906204-c770e365-a354-419a-b2d2-2264b29b478d.png">
> 
> If we don't maintain old sites anymore, it's okay.

I removed the image, so it should be fine now.
