### ISSUE TITLE
auto hide the welcome notice in neve after a site is imported

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#178]
### Description:
right now, once we import a website, we show the neve notice which I don't is required anymore since the notice was mentioning the to try one of our starter sites, which the user already did. I think once the import is finished, we can hide the notice.

The behavior can be replicated by using a fresh install with only the TPC plugin.

@mghenciu @JohnPixle @Codeinwp/theme-dev what do you think?

**Comment by preda-bogdan** [comment]
I think it makes sense and it should be straight forward to implement. I think we can set an option after import is finished. And hide the notice based on that.

**Comment by selul** [comment]
@preda-bogdan or maybe use the same option that is used for show/hide the notice.

**Comment by preda-bogdan** [comment]
Will do.
