### ISSUE TITLE
Image options

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#190]
[While investigating the issues with demos importing](https://github.com/Codeinwp/demo-data-exporter/issues/92#issuecomment-1123657444), @preda-bogdan found that the issue is coming from some differences in the Image Options (inside the editor), that cause those images to have 404 error on import.

In this case we are talking about the [Medicare Site](https://demosites.io/medicare-gb/).
And the option that's causing the issue is **Image size**, 
### which looks like this on demosites.io:
![Screenshot 2022-05-12 at 18 27 43](https://user-images.githubusercontent.com/52494172/168111877-425b3b64-1ff1-479f-9beb-a0ddc83c35b8.png)

This is from a gallery block:
![Screenshot 2022-05-12 at 18 21 37](https://user-images.githubusercontent.com/52494172/168110612-7f3dfc0b-23e5-4a2b-9bfd-beff309f6005.png)

### and on a clean test instance, the Image Options look different (causing the errors):
![Screenshot 2022-05-12 at 18 27 20](https://user-images.githubusercontent.com/52494172/168111932-4bad2bcd-93eb-47be-b515-2589ab7f18ab.png)

![Screenshot 2022-05-12 at 18 24 11](https://user-images.githubusercontent.com/52494172/168111103-66296297-c1d9-4afe-8100-fb57e0816be6.png)

Now the question is what is causing this? is it Otter or wp.
Would help to know, because we were using those settings on demosites.io, but apparently this is causing issues after import (image have 404 errors).

___
Both instances run Wp 5.9.3
and Otter 2.0.2

___
just fyi @JohnPixle

**Comment by HardeepAsrani** [comment]
@preda-bogdan Seems like this is due to image importing from TPC aren't forcing WP to regenerate thumbnail styles, so only the original image size is imported.

**Comment by preda-bogdan** [comment]
We can trigger a regenerate on attachments programmatically on import.

**Comment by preda-bogdan** [comment]
I've created a fix for this.
We had a filter that we previously used to speed up the import that was removing the sizes. I've detailed all my findings on this PR #192.

@mghenciu After we merge this you should be able to use the default image sizes on the demo sites ( thumbnail, medium, large)

@selul From my understanding after asking @abaicus about this we added the filter to speed up the import. Do you see any issues with just having a few specific sizes instead?

**Comment by preda-bogdan** [comment]
@mghenciu a note here only `thumbnail` and `medium` should be available alongside `full size`.

**Comment by mghenciu** [comment]
Thank you, @preda-bogdan .
So it's safe to use now any of those for images?

**Comment by preda-bogdan** [comment]
Yes
