### ISSUE TITLE
Improve the publishing pages flow for our content team

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#194]
### Description:

As discussed on [this issue ](https://github.com/Codeinwp/templates-patterns-collection/issues/164), it would help to have a way of automatically generating the Screenshots when we (Themeisle admin) uploads page in the TPC (attached the pages link I am referring to)
<img width="1558" alt="Screenshot 2022-12-23 at 14 35 19" src="https://user-images.githubusercontent.com/52494172/209338344-33141f21-b561-4497-b403-d14acda70c3e.png">

___

I am open to any news or thoughts on how we can approach this?
Essentially the challenge is the fact that (we, as Themeisle admins) to add a Demo pages in Templates cloud, need to:

- take a screenshot of the demo and adjust it's size
- go on that page in edit mode
- add the entries like site slug & modified screenshot url
- and this takes some time.

The ideal solution would be that we have a license/account just for upload, and that account only need to go on the page in edit mode, add the site slug - press publish, and the screenshot will be generated -> page published.

### Alternatives:

Do nothing

**Comment by preda-bogdan** [comment]
For the new workflow you can add `{generate_ss}` to the Screenshot URL, it will allow publishing the template and generating the screenshot.

If a path is passed it will work as before skipping screenshot generation.

The screenshot generated uses the same Job as for the regular templates but for the premade templates instead of returning the path to S3 where the screenshot is generated, it will return an api.themisle.com path. This is dependent on some changes to the lambda to allow forwarding the paths to the Optimole service as previous images witch are hosted on demosites.io.

Before releasing we will need to add the S3 bucket domain to the allowed domains for the Optimole distribution.

Let me know if you have any feedback regarding the current workflow.

Thank you!

**Comment by mghenciu** [comment]
The workflow sounds good, Bogdan 🚀  Definitely much better compared to making and adding them manually.

I would probably just need to check how the results look, when an automatic screenshot is generated. I can do that when we have a build, or we can add small enhancements after the initial release.

**Comment by preda-bogdan** [comment]
Here is an autogenerated screenshot from my tests: http://template-cloud-test.s3.amazonaws.com/templates-data/2023/01/ebf0233ced7259cf0838b7ba6d3aee075il462sqfcr0aa648yw0/screenshot.jpg and this is the preview inside the Templates page 
![image](https://user-images.githubusercontent.com/23024731/215145032-67cd0807-6f2a-4436-9b2b-a2cd5e8ce93b.png)

**Comment by mghenciu** [comment]
The preview **looks very good**, Bogdan, thank you!

Just a quick question, would it be possible to have some kind of ?optml_off=true for the Palette Switcher, and basically run on our end the Screenshot generation without the palette switcher icon:
<img width="780" alt="Screenshot 2023-01-30 at 12 25 20" src="https://user-images.githubusercontent.com/52494172/215451618-c1167b02-6ee2-4271-a2fc-f58043c583a2.png">

If this would require too much rework, we can leave as it is.

**Comment by preda-bogdan** [comment]
Here this should now be available with the latest release of TPC. We can test it with some templates and check if the screenshot gets generated on production.

**Comment by mghenciu** [comment]
I tried Bogdan today, to Publish a page with the screenshot generated - **but it didn't worked as expected**.
Not sure if I missed something (attached video): 

https://user-images.githubusercontent.com/52494172/216940161-b7692fce-f92e-4938-8603-df63a73ebec0.mov

Let me know if I can help with anything else.

**Comment by preda-bogdan** [comment]
@mghenciu There is an issue with the screenshot job not working anymore, will follow up once this is resolved. You will see that no screenshots are being generated for the regular templates.

**Comment by preda-bogdan** [comment]
@mghenciu I tested I think there is an issue with the delay, the job might not execute as soon as the data is requested. Can you try the following:
1. Save a template
2. Publish the template with `{generate_ss}`
3. Refresh the editor
4. Unpublish the template and see if the screenshot URL is filled with an URL after unpublish.
5. Publish with the new URL

If this works for you I will look into solving the delay issue. Let me know, thank you!

**Comment by mghenciu** [comment]
Yes, **it worked** using the steps mentioned above.

I've published the Contact page from the [Business demo](https://demosites.io/business-gb), to test this:
<img width="1614" alt="Screenshot 2023-02-10 at 13 00 23" src="https://user-images.githubusercontent.com/52494172/218076013-278897e2-281b-4de2-821a-181d060b190f.png">

**Comment by preda-bogdan** [comment]
Ok, I'll look into waiting for the job to finish to improve the user experience but you can use this if you don't want to take the screenshot manually.

**Comment by preda-bogdan** [comment]
@mghenciu You will now have access to a new button to refresh the data after publishing for cases where the image is not immediately available. Let me know if you encounter any issues with the latest release. If there are no problems we can close the issue. Thank you!

**Comment by mghenciu** [comment]
Looks ok, Bogdan.
I've saved now the pages for 2 demos, and it works. Sometimes I need to do the refresh twice, so the Screenshot url appears in the input field - but in the end it works.

So we can close this, as it's improves the Screenshot generation 🚀

**Comment by mghenciu** [comment]
Tried today to save the pages on this demo: https://demosites.io/architecture-studio-gb and on the Elementor version - **but it didn't worked**.

The workflow looks to be working in front-end (the refresh notification appears), but not in the backend:
![image](https://user-images.githubusercontent.com/52494172/219613703-952a433c-b559-4369-8de8-e238b3bfea4e.png)
___
![image](https://user-images.githubusercontent.com/52494172/219613761-2628eef6-1afc-483e-a528-1be9eaa4e154.png)

**Comment by mghenciu** [comment]
There may be an issue again with the screenshot flow, @preda-bogdan.

I tried today to save some pages in the Cloud, both from a Neve Pro account (as an user) and also tried to publish some pages in Templates Cloud (as a Themeisle admin) - and same issue on both flows, the screenshot is not generated (attached) video:  

https://user-images.githubusercontent.com/52494172/223169192-85ce24d5-a66e-4137-a242-7ff0f20cbfd6.mov
