### ISSUE TITLE
[Question] Duplicating pages and sync UIX flow

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#198]
### Description:

If my memory is correct, I think we discussed about this before.
There may be an issue to how we handle Items/pages linking in the cloud. **The issue comes when as a user, I try to duplicate a page that's already synced in the cloud. This will create a clone, that will still be linked in the cloud,** meaning that at this point there are 2 upcoming streams. And saving from each of those, will overwrite the Cloud save.

In our case, this issue happens when we duplicate a Site on demosites. For example in this case I duplicated Web Agency to Web Agency Pro, and as seen below, pages keep the connection even if I didn't knew about this: 
### Web Agency (origin)
![Screenshot 2023-01-16 at 16 22 13](https://user-images.githubusercontent.com/52494172/212700376-a101d972-82df-402b-8cee-ea54b0dcfd64.png)

### Web Agency Pro (clone)
![Screenshot 2023-01-16 at 16 19 59](https://user-images.githubusercontent.com/52494172/212700402-b9255148-da59-4d78-9ef5-1c4b7e9d7e1b.png)

___
Now, let's say not a lot of users will use this flow with a Multi Site context.
But same thing happens if a user will do the a clone with just a page. For example:
- if I have a Page synced in Cloud
- I use a duplication plugin to duplicate the synced page
- later I try to edit the clone
- **the Clone will keep the original link** and Unpublish probably de-lists the original page

A potential solution could be that on Clone, the link is reset.
Or we can have a button/option in the UI - to unlink a page, and create a new record/sync in cloud with it.

___

### How to reproduce:

1. On a multisite instance, clone a site that has pages synced in Cloud
2. After that, on the clone, open a page in edit more
3. Notice that the link is still present

### Expected behaviour:
It should be possible to Clone pages without worrying about the fact that those are linked in the Cloud.
For example let's say I have a 404 page in the cloud, and I want to create 3 variations. I would clone the original one and adjust the rest of them - but for sure I wouldn't start from scratch.

### Technical info
* WordPress version: 6.1.1
* Theme version: 1.1.30 

@JohnPixle , **let me know when you have some time if this issue makes sense** - as you have more experience working with the TPC upcoming redesign.

**Comment by preda-bogdan** [comment]
Here I think meta related to templates cloud should be stripped when cloning pages.

**Comment by mghenciu** [comment]
In our case, **we are cloning sites on a multisite instance**. But I think the same principles should apply, meaning that there should be only 1 upstream source - not multiple, even if I a page/site is cloned multiple times.

**Comment by selul** [comment]
I think is good as it is for now, we can look further if this is becoming a major pain point.

**Comment by mghenciu** [comment]
> @mghenciu Let me know if this would work for you.

I am not 100% sure I understood the technical part.
**In our case we can still go the manul way, meaning that when we duplicate a site, we'll first remove the existing pages** and create new ones. Making sure this way that any connections for the duplicated pages are removed.

I tried testing this with an VIP license (from a user perspective), and it doesn't look to be a problem when duplicating pages inside the same site. Didn't tested how this would work if the user clones the site on a multi-site.

**Comment by irinelenache** [comment]
@preda-bogdan Tested and the issue is fixed for me, both when using a multisite or a normal website 🚀
