### ISSUE TITLE
[Question] Builder based starter sites included in the plugin

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/templates-patterns-collection#199]
### Description:

It’s written in the description of [this](https://wordpress.org/plugins/templates-patterns-collection) plugin that we provide templates and starter sites based on Elementor, Beaver Builder, Brizy, Gutenberg, Divi, and Thrive builder. Currently, we have only Elementor and Gutenberg-based templates. However, we have some page templates based on Beaver builder. 

The description should be edited on WordPress.org according to our plan >> https://wordpress.org/plugins/templates-patterns-collection

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani here's the old text:

> Free and premium templates and starter sites available for top 5 page builders: Elementor, Beaver Builder, Brizy, Gutenberg, Divi and Thrive.
All templates can be previewed on [demosites.io](https://demosites.io/) and you can seamlessly import to any of your site.

I suggest changing it to:

> Browse a wide selection of templates and starter sites that are designed to help you build beautiful websites with Elementor and Gutenberg. All templates can be previewed on demosites.io and you can seamlessly import them to any of your sites. Whether you're a beginner or a seasoned pro, our templates can help you save time and create stunning websites without any coding knowledge.
> In addition to our Elementor and Gutenberg templates, we also offer a handful of page templates for Beaver Builder. These templates are perfect for creating basic pages such as contact pages, about pages, and blog pages. If you're a Beaver Builder user, be sure to check out our selection of page templates.

Let me know what you think.

**Comment by HardeepAsrani** [comment]
Just to confirm @Codeinwp/marketing, let me know if that sounds good to you.

**Comment by atikurTonmoy** [comment]
I think @cristian-ungureanu's revised description is much more accurate and aligns better with our current offerings. Nicely written!

**Comment by HardeepAsrani** [comment]
Awesome, thanks for quick confirmation! @cristian-ungureanu we can go with it.
