### ISSUE TITLE
Bug: Estatik import

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/templates-patterns-collection#200]
### Description:

It looks like the newer versions of Estatik hook on plugin activation and do a hard redirect that will break the install process. 

### How to reproduce:

1. Import Real Estate Agency on a fresh instance
2. Check that the install breaks

Note: the plugin will install and activate so if you refresh and try again it will import the Demo
### Expected behavior:
Not break on the first install.

### Current behavior:
Break on the first install.

### Technical info
* WordPress version: x.x.x
* Theme version: x.x.x

**Comment by purplecodes** [comment]
+1 https://secure.helpscout.net/conversation/2129829469/352877/
