### ISSUE TITLE
importing issue with newest version

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#204]
@preda-bogdan @irinelenache Sorry to say this, but it still doesn't work for me 🥲 I created multiple instances, on both tastewp and instawp. None of the Elementor templates can be imported for me and some of the Gutenberg ones (for example Recipes Blog, NFT Illustrator, Real Estate Agency, Jewellery Shop, University, Job Board, Resume 2, Architecture Studio) throw that error as well.

Here is a tastewp instance:
 Admin area URL: https://thinkvan.s2-tastewp.com/wp-admin 
 Username: luciamarinescu 
 Password: E81uztgmrdc 

And a instawp instance, even if there is no difference regarding the behaviour between them:
URL : https://us-opossum-reva.instawp.xyz
Username : lijifiyosa8810
Password : tYjLXNDK5TqwBzJRxUHl

_Originally posted by @MarinescuLucia in https://github.com/Codeinwp/templates-patterns-collection/issues/201#issuecomment-1398306198_

**Comment by selul** [comment]
@preda-bogdan  added this here to keep track

**Comment by preda-bogdan** [comment]
@selul Thank you I'm already investigating this, I will post an update soon

**Comment by preda-bogdan** [comment]
Closing this as it was solved and released we can reopen this one if there are other cases tied to license checking.
