### ISSUE TITLE
The Legacy Starter Sites don't appear anymore

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#205]
### Description:

With the current version of the plugin, and the plugin for Legacy Starter Sites installed, the legacy templates don't appear. For example, I've searched for the Travel Agency template that was useful for the migration from Zelle to Neve.

### How to reproduce:

1. Install & activate Templates Patterns Collection
2. Install & activate Themeisle Starter Sites Legacy
3. Search for a legacy template such as Travel Agency, you won't find it

### Expected behaviour:

To find the Travel Agency template and other legacy starter sites.

### Current behaviour:

![Markup on 2023-01-24 at 11:59:00](https://user-images.githubusercontent.com/26867648/214262468-6a1fd31a-e972-400f-a779-9ce4e6579f61.png)

### Reference:

![Markup on 2023-01-24 at 11:55:40](https://user-images.githubusercontent.com/26867648/214261759-a8cd56c1-0bca-456b-aead-2cb1bff14926.png)

https://secure.helpscout.net/conversation/2131594727/353121/
https://secure.helpscout.net/mailbox/dd8c59516d047fb2/chats/224d247e-cbcc-4e3c-bacd-20880a64b817
https://secure.helpscout.net/conversation/2146624368/355031?folderId=212390

### Technical info
* WordPress version: 6.1.1
* Plugins version: 1.1.32

**Comment by selul** [comment]
@stefan-cotitosu yes, that's correct they were part of a transition time, we haven't planned to support them forever.

**Comment by stefan-cotitosu** [comment]
Can we add at least the Travel Agency one back? Right one, it only remained available in Elementor, for Zelle users. With this starter site, they can transition to Neve by using Gutenberg and Otter.

Maybe it's easier to add it in the current selection of sites rather than ending the legacy plugin?

Also, should I remove this doc? https://docs.themeisle.com/article/1613-where-do-i-find-the-legacy-the-starter-sites

**Comment by stefan-cotitosu** [comment]
By available in Elementor I mean it can be downloaded from this documentation - https://docs.themeisle.com/article/560-how-to-duplicate-front-page-sections-in-zelle-pro

**Comment by selul** [comment]
@preda-bogdan can you help with this when you get some time, we can consider this free for legacy  if it helps to simplify the flow.

**Comment by preda-bogdan** [comment]
I will just move that Starter Site to Free for Elementor to allow users to migrate. To allow access to other legacy sites we would need to change the lambda function. So just having it as Free although it is not actively maintained I think it is ok. Will link back a PR for this.

**Comment by stefan-cotitosu** [comment]
Bogdan, it will help for the Travel Agency starter site built in Gutenberg to be available again in the library. This way, users can import it in Neve and continue with Otter. Thank you!

**Comment by preda-bogdan** [comment]
@stefan-cotitosu updated to only allow the Zelle template for Gutenberg since that is the one being used for the upgrade. Thank you!
