### ISSUE TITLE
Small enhancement for the TPC wizard in Elementor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#239]
### Description

The TPC wizard in Elementor is a little bit different than the one in the block editor.
In the block editor
<img width="1460" alt="Screenshot on 2023-04-04 at 10-53-07" src="https://user-images.githubusercontent.com/3266155/229747163-1946380c-2010-4bd9-8bbd-1e2d86f627be.png">
In Elementor
<img width="1480" alt="Screenshot on 2023-04-04 at 10-48-13" src="https://user-images.githubusercontent.com/3266155/229747222-8a6cd4be-4c74-45c0-bbbd-36bb1b53abbe.png">

### Step-by-step reproduction instructions

In Elementor:
- the color of the text is barely visible ( especially in the search bar, where the text is very small, you can't see what you are typing)
- The _No templates found_ message is not aligned with the _SORT BY_ text, as it is in the block editor.

### Is the issue you are reporting a regression

No

**Comment by preda-bogdan** [comment]
**A note here:** I added the large label here, as I found some other styling issues in the Elementor modal and want to also fix those. Will mention every change on the PR.
