### ISSUE TITLE
Spacing missing in Web Agency GB demo 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#242]
### Description

On internal pages, some spacing is missing
https://demosites.io/web-agency-gb/web-agency-gb-portfolio/
https://demosites.io/web-agency-gb/web-agency-gb-about-us/

### Step-by-step reproduction instructions

How it currently looks
![Annotation-Annotation on 2023-04-06 at 11-05-29 png](https://user-images.githubusercontent.com/3266155/230314798-9ef2ddd7-2519-42dd-9b13-7b3334a0864f.png)
![Annotation-Annotation on 2023-04-06 at 11-04-28 png](https://user-images.githubusercontent.com/3266155/230314817-f5cdeb88-bc3b-4bec-ad30-a1f2171747e2.png)
![Annotation-Annotation on 2023-04-06 at 11-02-26 png](https://user-images.githubusercontent.com/3266155/230314837-b65ceb94-bbb8-42be-bd45-3bd9d0a79883.png)

### Screenshots, screen recording, code snippet or Help Scout ticket

How it used to look like ( from web archive )
![Annotation-Annotation on 2023-04-06 at 11-03-04 png](https://user-images.githubusercontent.com/3266155/230315020-6af42a48-b795-40c7-a243-5daafd40c727.png)

@mghenciu 

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by mghenciu** [comment]
**Should be good now.**

The issue was coming from the fact that in the previous versions of Gutenberg and/or Wordpress, all the images had a bottom margin. In the recent releases this was changed to 0px - and that's causing issues like this.
It looks ok now, as I've added a spacer under most images, but it may look too much on sites with older versions of Gutenberg and/or WP.

**Comment by rodica-andronache** [comment]
@mghenciu the demo looks good now 👍 
I guess for the default content installed with Neve ( when you first go to customizer on a fresh install ) and visible on https://wordpress.org/themes/neve/ I would need to create a new separate issue as that is coming from the theme, right, not the demo?

**Comment by mghenciu** [comment]
> https://wordpress.org/themes/neve/ I would need to create a new separate issue as that is coming from the theme, right, not the demo?

Yes, that one is made only using Gutenberg (no Otter involved), and from what I know it's coming from code/somewhere else - **not from the web agency demo**.

**Comment by mghenciu** [comment]
@rodica-andronache , I checked all the Gutenberg pages from all demos - and added spacer under images where needed.
After the sync up, when the QA team has some time, it would help to test the demos - in case I missed something.
