### ISSUE TITLE
Color issues in Beaver Page Templates

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#244]
### Description

There are various color issues in most of the Beaver Page Templates
![Annotation-Annotation on 2023-04-18 at 11-12-00 png](https://user-images.githubusercontent.com/3266155/232716048-1e735911-407f-4478-9327-7901caf953ba.png)

Some examples:
<img width="1226" alt="Screenshot on 2023-04-18 at 11-06-43" src="https://user-images.githubusercontent.com/3266155/232715599-02aec207-a367-4e07-a0fb-5adcb273e981.png">
<img width="1269" alt="Screenshot on 2023-04-18 at 11-07-03" src="https://user-images.githubusercontent.com/3266155/232715666-7a93e0d2-775f-410b-8556-1342cbc8e3d3.png">
<img width="1436" alt="Screenshot on 2023-04-18 at 11-07-30" src="https://user-images.githubusercontent.com/3266155/232715710-d19e0754-9e60-44cb-8f04-a2e106b3c370.png">

### Step-by-step reproduction instructions

Go to Appearance > Starter Sites > Page Templates > Beaver
Preview some of the Page Templates

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by HardeepAsrani** [comment]
Hey @rodica-andronache,

I tested it on Chrome and Firefox and they seem to work properly:

<img width="776" alt="Screenshot 2023-04-20 at 5 01 09 PM" src="https://user-images.githubusercontent.com/2649903/233353396-23d01f8d-e49f-4fae-bd98-94012e5c1014.png">

I tried with few templates and seems to work fine. Are you having this with all browsers or anything in particular?

**Comment by rodica-andronache** [comment]
@HardeepAsrani I can't replicate it anymore, not sure what happened, but I'll close it for now. Thanks for checking!
