### ISSUE TITLE
Starter sites various design issues

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#245]
### Description

Various design issues for the Starter Sites @mghenciu  

### Step-by-step reproduction instructions

Gutenberg

- [x] https://demosites.io/conference-gb/contact/ - contact form button color is white on white

- [x] https://demosites.io/resume-gb/services/ Hover state https://vertis.d.pr/i/TEDWYE

- [x] https://demosites.io/shop-gb/ very small size for the prices

- [x] https://demosites.io/fitness-trainer-gb/ - white text in one section

- [x] https://demosites.io/drone-gb/checkout/ labels are white on white

- [ ] https://demosites.io/product-launch-gb/ https://vertis.d.pr/i/xsW6Wy

___
Elementor

- [x] https://demosites.io/speed/ - footer spacing

- [x] https://demosites.io/medicare/contact-us/ - Book Appointment link in the main menu is broken

- [x] https://demosites.io/industrial/hello-world/ - Get a Quote button in the menu links to GB demo

- [x] https://demosites.io/drone/checkout/ - labels are white on white

- [x] https://demosites.io/craft-beer/ the first front-page section looks broken compared to https://demosites.io/craft-beer-gb/

- [x] https://demosites.io/jewellery-shop/ https://vertis.d.pr/i/mYUzHE - text is white on white for the search bar from the menu

- [x] https://demosites.io/accounting/ - the first front-page section looks broken compared to https://demosites.io/accounting-gb/

- [x] https://demosites.io/product-launch/ the first front-page section looks broken compared to https://demosites.io/product-launch-gb/

- [x] https://demosites.io/restaurant/restaurant-menu/ - last section has the text barely visible

- [x] https://demosites.io/lawyers/lawyers-contact/ - map is not visible

- [x] https://demosites.io/conference/ the first front-page section looks broken compared to https://demosites.io/conference-gb/

- [x] https://demosites.io/pet-shop/ - the menu looks to be not aligned as https://demosites.io/pet-shop-gb/

- [x] https://demosites.io/yoga-studio/yoga-studio-classes/ https://vertis.d.pr/i/zhutqG

- [x] https://demosites.io/yoga-studio/yoga-studio-contact/ - map is missing

- [x] https://demosites.io/vacation-rental/vacation-rental-location/ - map is missing

 

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by mghenciu** [comment]
Thank you, Rodica, for testing. 
I'll take a look in a while.

Please make sure to add items as Todo list, if the the list is longer - as it easier to track the progress on them, as usually I solve this in batches 🚀

**Comment by mghenciu** [comment]
This isn't an issue, if you are referring to the white borders - as the lines were added as a design choice.
 https://demosites.io/product-launch-gb/ https://vertis.d.pr/i/xsW6Wy
