### ISSUE TITLE
Error Notice on Full Site Editing editor

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/templates-patterns-collection#246]
### Description

When working in the FSE editor, an error notice appears at the top.

### Step-by-step reproduction instructions

1. Have TPC installed.
2. Enter any Template in the FSE editor.

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://user-images.githubusercontent.com/17597852/234262439-91990a69-9c32-43f3-bae9-93cb5fc39d1f.png)

### Environment info

https://pastebin.com/hhM7dv2Y

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
It seems to be breaking here: https://github.com/Codeinwp/templates-patterns-collection/blob/8b9da8d4c07b063ab750322e3bac595d17e8ed8f/editor/src/extension.js#L137 - given postType isn't available here. Until we decide to support the Templates Cloud saving feature on FSE, we can disable it on FSE editors and create a new issue about FSE support.

**Comment by preda-bogdan** [comment]
@HardeepAsrani Created a PR to solve the issue and opened a new issue to improve FSE support in the future.
