### ISSUE TITLE
Add documentation link after Starter Site Import

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/templates-patterns-collection#247]
From now on, we will create short pieces of documentation for the starter sites, hoping to help the user get an overview of the plugin stack and the overall starter site setup. 

In  the last step of the import wizard, we will need to add a notification with a link, as the screenshot below shows.
![screenshot_2023-04-24_at_12 41 31_pm](https://user-images.githubusercontent.com/4193672/234336087-7360e269-587a-4cab-b920-e13424fcc0f6.png)

[Figma.](https://www.figma.com/file/QklXyJh0XHVzq2h4IpPNaz/Neve-options?node-id=4032%3A24079&t=AGHFNIij3zhR1ZjT-1)

### Backend
In the backend, we will need to add an option to add a link, quoting Mihai from Slack:

> Probably this can be enabled via the [TPC plugin](https://github.com/Codeinwp/demo-data-exporter/blob/master/front-end/class-dde-frontend.php), similarly how we do it for the page templates; and have the option for a link.

![screenshot_2023-04-24_at_12 47 51](https://user-images.githubusercontent.com/4193672/234336272-dfac43dc-9a6a-419d-bd4a-0b892ecb32ce.png)

cc @mghenciu

**Comment by vytisbulkevicius** [comment]
Suggested here - https://github.com/Codeinwp/neve/issues/3956
