### ISSUE TITLE
My Library appears under Appearance > Neve Options

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/templates-patterns-collection#262]
Now that Neve settings have been moved to a dedicated panel, the Templates Cloud activation triggers Neve Options to appear under Appearance.
I created a video to showcase this behavior - https://www.loom.com/share/9d02e8dea40f47148eb62f320403145c?sid=7a871aac-9e42-434a-a0a4-c4528c215646

My question is: Is it okay to duplicate Neve Options under Appearance only for the Templates Cloud to work there?

I see two cases:

- using Neve - the My Library menu will appear under Dashboard > Neve
- using a different theme - the My Library menu will appear under Appearance

Let me know what you think!

**Comment by rodica-andronache** [comment]
hi @AndreeaCristinaRadacina I think this is related to https://github.com/Codeinwp/templates-patterns-collection/pull/261 which was not released yet.

**Comment by HardeepAsrani** [comment]
Closing it as it should've been fixed in the latest release.
