### ISSUE TITLE
Starter sites page isn't working using WP lower than 5.4

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#273]
### Description

If i'm using a WordPress version lower than 5.4, the starter sites page will be empty https://vertis.d.pr/i/fUhERw . On wp.org the minimum wp version is [4.7](https://vertis.d.pr/i/dhN5tU) so i think we can raise it to 5.4

### Step-by-step reproduction instructions

1. Install a WordPress version lower than 5.4
2. Try to access the starter sites page in dashboard

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/fUhERw

### Environment info

WordPress lower than 5.4 / PHP 7.0 / TPC 1.1.39

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
We can bump it to 5.4, thanks Irinel for testing!
