### ISSUE TITLE
add ordering for templates and sections

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#28]
### Description:
Based on the wireframe we can have ordering in the page templates/sections and my library area. 

We can two set of orders, created/modified both ASC and DESC.

**Comment by HardeepAsrani** [comment]
<img width="1680" alt="Screen Shot 2020-11-28 at 3 47 52 AM" src="https://user-images.githubusercontent.com/2649903/100486996-93a02480-312c-11eb-8295-0c7d720939b9.png">

@selul @JohnPixle Is it fine if it looks like this? There isn't much on, at least for this particular release, in the "My Library" page to show. If we keep it on left it looks even worse. What do you think?

**Comment by HardeepAsrani** [comment]
Should be addressed by this PR: https://github.com/Codeinwp/templates-patterns-collection/pull/31

**Comment by HardeepAsrani** [comment]
Here's how it looks in the main library (outside the editor). The above picture shows how it looks inside the editor.

<img width="1084" alt="Screen Shot 2020-11-29 at 10 18 23 PM" src="https://user-images.githubusercontent.com/2649903/100548143-ce22d200-3290-11eb-97e1-8c096c072e86.png">

**Comment by selul** [comment]
@HardeepAsrani Looking great! 

Both the dashboard and editor popup should have search + order.

We should also have order by the last modified date, not just by creation. 

Also, ordering should be available for Page template/sections/my library

**Comment by HardeepAsrani** [comment]
> We should also have order by the last modified date, not just by creation.
- I agree. In fact, we can also have it in alphabetical order. However, for that it must be available in the API first. Did we add that to the API or we need to add that first?

> Also, ordering should be available for Page template/sections/my library

- Do you mean the Starter Sites tab? It's available for Page Templates & My Library.

**Comment by HardeepAsrani** [comment]
I don't see the order supporting support in API, nor we storing modification date there. Regardless, the options have been added. If someone wants to add more ways, they just need to add the sorting param to the code here: https://github.com/Codeinwp/templates-patterns-collection/pull/31/files#diff-6e256789d1d0dd55b19da2ee3c989fe7dee2a38c0d0ff5eebdd3ef6bfe8c9e9cR5

**Comment by selul** [comment]
Yes, last modification is not added to the api, we need to add the column there too to implement the feature.

**Comment by HardeepAsrani** [comment]
Until they're added, I can add the search feature. However, search only works with the Templates, not Section, as there's no support for search. We need to add those to the API.

**Comment by HardeepAsrani** [comment]
Search parameter was added to the API via https://github.com/Codeinwp/templates-cloud/commit/f88e5af3b93c19a97d7a0b7a555f00a9281e3a9c

**Comment by HardeepAsrani** [comment]
Added `modified` column & `orderby` param to the API: https://github.com/Codeinwp/templates-cloud/pull/12/commits/a81f00b7b167c98d5dcccf9c132e02d14867883c
