### ISSUE TITLE
Changes/Improvements to Onboarding

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/templates-patterns-collection#288]
### What problem does this address?

Based on the feedback received, here are things that we need to address in the Onboarding wizard. It should be noted that we can estimate this issue and if the estimate is larger than medium we can split this into multiple smaller issues and proceed.

### What is your proposed solution?

- [x] **Top Header Issue:** The top header of the onboarding process interferes with the starter site preview. It gives the impression that the white bar is part of the starter site itself.

Please refer to this comment for the changed design: https://github.com/Codeinwp/templates-patterns-collection/issues/288#issuecomment-1735176864

<img width="1651" alt="Screenshot 2023-09-25 at 10 01 24 PM" src="https://github.com/Codeinwp/templates-patterns-collection/assets/2649903/09eaf5f0-bbc7-4f83-95e6-36dfc0b8c6d7">

---

- [x] **Next Step Button:** On full screen, the ‘Next Step’ button is not visible without scrolling down. This could frustrate users and increase the drop rate.
<img width="2553" alt="Screenshot 2023-09-25 at 10 05 39 PM (2)" src="https://github.com/Codeinwp/templates-patterns-collection/assets/2649903/a010b5fd-ba4c-4447-9ca9-6aaad3de211d">

We can ensure that the button always stays in the view (floating on the bottom), and is inclusive of all the screens with similar buttons.

---

- [x] **Missing UTM Tags:** We can revisit the code to confirm no external links are missing UTM tags, an example [here](https://github.com/Codeinwp/templates-patterns-collection/blob/6d79cde9abb184f4e0e4270e5617dd5b6d43f330/onboarding/src/Components/SiteSettings.js#L201).

---

- [x] **Textarea in Logo Section:** The textarea in the logo section doesn’t make sense as it doesn’t allow URL input. It only activates with the ‘Browse’ button. Also reported at https://github.com/Codeinwp/neve-pro-addon/issues/2634

Please refer to this comment for the changed design: https://github.com/Codeinwp/templates-patterns-collection/issues/288#issuecomment-1735176864

![Annotation-Annotation on 2023-09-25 at 18-46-38 png](https://github.com/Codeinwp/templates-patterns-collection/assets/2649903/df17a7fb-548a-4878-b759-9325858114df)

---

- [x] **Missing Shadow/Border:** During the preview, the sidebar doesn't have any shadow/border, which doesn't look right. Similar to what we have in the header, we can have some shadow or border here to make the hierarchy clear as it stands in the Figma mockup.

<img width="830" alt="Screenshot 2023-09-25 at 10 11 13 PM" src="https://github.com/Codeinwp/templates-patterns-collection/assets/2649903/fa5a6ee2-51cd-4f05-b4bc-8470e83b230a">

---

- [x] **Thumbnail Size in Larger Display:** The thumbnail ratio in larger displays isn't ideal and can be improved to look more natural than it currently is, or we could display more sites there to avoid it looking stretched.

<img width="2560" alt="Screenshot 2023-09-25 at 10 11 06 PM" src="https://github.com/Codeinwp/templates-patterns-collection/assets/2649903/7466838f-db97-4d70-85b1-276af0922adc">

### Will this feature require documentation? (Optional)

None

**Comment by vytisbulkevicius** [comment]
For the:

> Textarea in Logo Section: The textarea in the logo section doesn’t make sense as it doesn’t allow URL input. It only activates with the ‘Browse’ button.

Marius suggested:

> Open the media modal automatically when this area is focused, or make the areas clickable [link](https://vertis.d.pr/i/Q0wart).

I also think that having the FULL URL there after you upload image doesn't make senter, we can
<img width="231" alt="image" src="https://github.com/Codeinwp/templates-patterns-collection/assets/36594177/297bb112-0203-424f-826f-2410db14cd2a">

I suggest showing only the name of the file without full URL as you can't change it there and it's not visible, scrolling in that input to see it full is not user-friendly.

**Comment by selul** [comment]
@JohnPixle it looks good for me.

**Comment by HardeepAsrani** [comment]
@JohnPixle They look great, and thanks for the prototype.

**Comment by cristian-ungureanu** [comment]
Than you, guys for the clarifications. The changes shouldn't take longer than medium. 🚀

**Comment by cristian-ungureanu** [comment]
Hey @JohnPixle, I have a question regarding this raised issue:

> Thumbnail Size in Larger Display: The thumbnail ratio in larger displays isn't ideal and can be improved to look more natural than it currently is, or we could display more sites there to avoid it looking stretched.

Maintaining the same aspect ratio of starter site cards on bigger displays doesn't look that good. Here's the result on a 2133px width screen:
![Screenshot 2023-09-27 at 14 15 05](https://github.com/Codeinwp/templates-patterns-collection/assets/9929553/d4d6dfbe-d4dd-4ee6-b898-c94ba9464d42)

I think the container should be limited too after a certain resolution.

**Comment by cristian-ungureanu** [comment]
Limiting the card to 400px will result in a [greater gap between elements](https://github.com/Codeinwp/templates-patterns-collection/assets/9929553/2f7979d2-633f-4e9c-934d-d691c74be065) unless we switch to a flex container ( there is a grid now ). With a flex container, the number of elements per row will be automatically established by the browser and the 400px limitation would work with a disadvantage of not being able to control the left and right margins: https://vertis.d.pr/i/eODFE3


Alternatively, we can keep the aspect ratio from the design ( 0.83 / 1 ), not limiting the card width and either:
- limit the container after a certain resolution to a fixed width:https://vertis.d.pr/i/TLdmvm
- Have more columns in the grid ( we decide how many and there will be no margin issues as in the flex case): https://vertis.d.pr/i/I24V0x. The disadvantage here is that for a really large resolution, we'll have the same issue as I posted in my previous message.

**Comment by cristian-ungureanu** [comment]
Ah, I'm sorry @JohnPixle, I found a better solution without switching to flex: https://vertis.d.pr/v/pfX3VO

I think we should go with this one: https://vertis.d.pr/v/pfX3VO
