### ISSUE TITLE
rename gutenberg save template

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#29]
### Description:
Let's rename the Gutenberg context menu for serving a template into the cloud from Save template into Save template to Neve Cloud

**Comment by selul** [comment]
Same thing for the page template

**Comment by HardeepAsrani** [comment]
@selul Templates Cloud or Neve Cloud?

**Comment by selul** [comment]
Let's use Neve Cloud until the concept gets more familiar.
