### ISSUE TITLE
Visual issue on starter sites with View Pages available

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#30]
### Description:

All the starter sites where the **View Pages** button is available have an additional line/box behind their thumbnail.

### How to reproduce:

1. Navigate to the **Starter Sites** page
2. Check a website that has **View Pages** available, like the Web Agency one
3. There is an extra box behind it
4. The issue seems to occur only for the starter sites where individual pages can be imported

<img width="1700" alt="starter-sites-visual-bug" src="https://user-images.githubusercontent.com/26867648/100377793-a32f4880-301a-11eb-928d-542523ced266.png">

### Technical info
* WordPress version: 5.5.3
* Theme version: 2.9.0
* Templates Patterns Collection: 1.1.0

**Comment by selul** [comment]
there is no visual bug, it is supposed to be like this as a distinct sign if we have pages inside that starter site or not. 
I.e it gives the impression of stacking, i.e of having multiple pages inside it. 

Starter sites without that effect do not have any page templates available.

**Comment by stefan-cotitosu** [comment]
Ok, it makes sens, I wasn't sure if it's on purpose, thank you for clarifying it. 👍
