### ISSUE TITLE
[WP 6.4] Page builder dropdown in starter sites lost styling

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#318]
### Description

Using WP 6.4, the page builder dropdown lost the styling https://vertis.d.pr/i/aLyQ6h . We had a similar issue in Neve's header builder https://github.com/Codeinwp/neve/issues/4107 

The issue is also present on demosites.io https://vertis.d.pr/i/Pkyy4Y

### Step-by-step reproduction instructions

1. Install TPC and go to starter sites
2. Check the page builder dropdown
3. Go to demosites.io
4. Check the page builder dropdown

### Screenshots, screen recording, code snippet or Help Scout ticket

Starter sites - https://vertis.d.pr/i/aLyQ6h
demosites.io - https://vertis.d.pr/i/Pkyy4Y

### Environment info

WordPress 6.4 / PHP 8.0 / Neve 3.7.3

### Is the issue you are reporting a regression

No

**Comment by preda-bogdan** [comment]
Thank you @irinelenache for reporting this, I already fixed this as part of this PR https://github.com/Codeinwp/templates-patterns-collection/pull/315. You can let me know if this happens for you with that PR, if not we can close this as it is already solved there.

**Comment by irinelenache** [comment]
@preda-bogdan Indeed, it's working fine with that PR, we can safely close this. Thank you 🚀
