### ISSUE TITLE
Dropdown Editor selector in Dashboard looks broken.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/templates-patterns-collection#320]
### Description

The popover that is used to display had some API changes, thus, the CSS selector and E2E are broken.

### Step-by-step reproduction instructions

1. Go to Starter Sites
2. Press on the dropdown that selects the Editor.

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://github.com/Codeinwp/templates-patterns-collection/assets/17597852/eae6b9ae-adaa-44fc-a4c9-aa0418628bf2)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by preda-bogdan** [comment]
This was already fixed here: https://github.com/Codeinwp/templates-patterns-collection/pull/315 will merge the changes and you can sync your branch.
