### ISSUE TITLE
Change update message in onboarding of starter sites

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/templates-patterns-collection#330]
### Description

As reported in this issue - https://github.com/Codeinwp/neve-pro-addon/issues/2729

There is a confusion created by the wording we use in the onboarding.
We have it here:
<img width="1511" alt="image" src="https://github.com/Codeinwp/templates-patterns-collection/assets/36594177/0795ab47-b793-4a06-927d-01fdc17546c5">

Or when we click on any PRO starter site and preview it:
<img width="489" alt="image" src="https://github.com/Codeinwp/templates-patterns-collection/assets/36594177/15767117-0d52-4849-8ed1-611b90c7db8c">

We need to upgrade the wording from:

From:
> Unlock Access to all premium templates with Neve PRO.

To:
> Unlock Access to all premium templates with Neve Business plan.

From:
> Upgrade to Neve Pro to enjoy unlimited access to all templates in the library.

To:
> Upgrade to Neve Business plan to enjoy unlimited access to all templates in the library.

Also, as @selul suggested on https://github.com/Codeinwp/neve-pro-addon/issues/2729#issuecomment-1890976348
it would be great to make this:

Keep the same pages/tables but hide the first plan if they arrive on the page based on any upgrade links from the Starter Sites context.

**Comment by vytisbulkevicius** [comment]
cc @harshitarora-in if you have any input about the wording used or approach in general

**Comment by selul** [comment]
@vytisbulkevicius, why do you think is relevant to mention the Agency as well? FMHO it looks confusing having that. If the previous texts(before the new onboarding) were well received and statistically clearer, why we can't use them and we need to invent new terminologies.

**Comment by selul** [comment]
https://vertis.d.pr/hleFPd this is how is used to be.

**Comment by vytisbulkevicius** [comment]
@selul, I didn't think mentioning both packages would cause confusion as we provide more information (that both packages Business or Agency) are options to upgrade. 
If we list only Business, there is a chance it could be questionable by some users whether they get it with Agency or not (it's clear from the pricing table but it's also clear from the pricing table that Starter Sites are not included so people are not looking into that carefully).

Also, as we mention Business explicitly maybe it works that they are looking for exactly this package to upgrade and not considering Agency.

I'm fine with having only Business mentioned but don't see confusion with mentioning both options.

**Comment by selul** [comment]
So, from your point of view, usually, when you pay a higher plan, you might get things removed vs the lower one? I have not yet encountered any situation where if I buy a higher plan, I don't get things available in the lower one, not sure if you have. 

My recommendation is based on past experience with the old messaging that we had and support feedback that those were clearer and less causing the confusion that we have now with naming which I thing is safes vs testing new messaging without any clear path of validating their success.

**Comment by vytisbulkevicius** [comment]
No, that's not something I experienced with the plans, I was putting emphasis on the fact that mentioning both plans that gives what they need shouldn't hurt and only give more clarity but let's follow your recommendation and use the old way that was working (the benefit with it is to have a shorter text).

(edited my suggestions in the issue description)

Thanks for the help
