### ISSUE TITLE
Sync button layout on hover on mac 12inch

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#36]
On hover, the text "Sync" appears, and it's not vertically aligned on a 12inch mac.
![Screenshot (1)](https://user-images.githubusercontent.com/3266155/102124937-93549880-3e51-11eb-9677-b9b66f198c6c.png)

**Comment by HardeepAsrani** [comment]
Which browser are you using? I wasn't able to reproduce it with screen size reduced on Firefox/Chrome/Safari.

**Comment by rodica-andronache** [comment]
I used to be able to reproduce this on both Chrome and Safari by resizing the screen, but now I can't replicate it anymore. @ineagu you still see this issue on your mac?

**Comment by cristian-ungureanu** [comment]
I managed to replicate this on BrowserStack on safari 13.1 and lower. I'll commit the fix right now.

**Comment by cristian-ungureanu** [comment]
Also, I don't know if using before for that button is the best solution, seems like before does not have great support on safari https://caniuse.com/?search=%3Abefore. cc @abaicus
