### ISSUE TITLE
Options to Save to template cloud not working anymore in latest WP version

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#371]
### Description

Related to https://github.com/Codeinwp/neve-pro-addon/issues/2833 I've also noticed, that in the latest version WP 6.6, the options to save a page/post to template cloud are not visible anymore

### Step-by-step reproduction instructions

1. On a WP 6.6 site, install TPC
2. Create a post and check to see if you have the TPC options in the editor

### Screenshots, screen recording, code snippet or Help Scout ticket

![Annotation on 2024-07-18 at 11-40-58](https://github.com/user-attachments/assets/723e8211-b085-4655-ae70-59f353a98805)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
@rodica-andronache I've reviewed and fixed it here https://github.com/Codeinwp/templates-patterns-collection/pull/370

**Comment by rodica-andronache** [comment]
@girishpanchal30 thank you. It's working now 👍
