### ISSUE TITLE
Tooltip text for Hyve is not visible, when importing a Starter Site

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#396]
### Description

![Image](https://github.com/user-attachments/assets/58c505cf-5d1a-43d1-a641-a450545ba732)

### Step-by-step reproduction instructions

Try to import a starter site. Only the text for Hyve is not visible, the others are visible.

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@rodica-andronache I've tested it with the development branch, and everything looks good to me.
![Image](https://github.com/user-attachments/assets/483e36d7-6277-4738-ab0e-4734ac86ad6d)

**Comment by rodica-andronache** [comment]
@girishpanchal30 I don't know how to get the build from development. I've tested with the current version from wp.org and it's not working for me

**Comment by girishpanchal30** [comment]
@rodica-andronache You can download from the last release - https://github.com/Codeinwp/templates-patterns-collection/pull/395

**Comment by rodica-andronache** [comment]
@girishpanchal30 yes, it's working well now 👍
