### ISSUE TITLE
Starter Sites not loading in Neve

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#399]
### Description

https://github.com/user-attachments/assets/bf11790c-41c5-494f-a542-ba03e792ffdb

The starter sites are not loading anymore. Not sure if there is a specific case, on one of my site it's still working.

### Step-by-step reproduction instructions

1. Install Neve
2. Go through the onboarding
3. Go to Starter Sites -> the sites are not loading

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
@abaicus fixed it, and it looks good now (tested on 2 different new websites).

Resolution comments for future:

> Deactivated breeze, resaved the permalinks, purged the cache on cloudways, and invalidated cloudfront.

**Comment by rodica-andronache** [comment]
@vytisbulkevicius this is not working again

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2752646457/439571?viewId=212385

**Comment by abaicus** [comment]
@rodica-andronache I emptied the cache. It should be fine now, but I suggest we monitor this so we can see if it happens again or there was just something wrongly cached.

**Comment by vytisbulkevicius** [comment]
@abaicus as Ionut mentioned on Slack this happened again, it doesn't work for me either. Can you investigate further on why this continues happening?
