### ISSUE TITLE
associate template with post metas subscribed by different providers

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#41]
### Description:
Right now when we save a certain template we save only the post content, not the associated metals, if any.

When saving the json of the content we should be able to add to the json a list of post meta which could be imported also. The list of post metas that are exported should be configurable, allowing us to build compatibilities with multiple other themes and plugins as well as turn this off completely from child theme or different plugins.

The main reason why we need to associate metas with template data is that in a lot of cases the design of the end page depends a lot of the post settings that were associated with the page. Importing just the content provides a whole different experience vs with meta.

**Comment by HardeepAsrani** [comment]
For Elementor is particular, you can import global values when you import a template. Haven't tried it but their own exports do support that.

**Comment by irinelenache** [comment]
@HardeepAsrani I didn't exactly understand how to test this. Can you give more instructions on this?

**Comment by HardeepAsrani** [comment]
@irinelenache You can leave this one, I've tested it
