### ISSUE TITLE
Dark mode affects contact form text color

### ISSUE THREAD

**Issue by tudor-themeisle** [Codeinwp/templates-patterns-collection#49]
### Description:

In dark mode, the primary accent color does not change, and text color turns white, making contact form text invisible.
You can change the text color in black, but then, you will not be able to see any text on the website.

### How to reproduce:

Contact us page - Customize - Colors & Background – Dark Mode 

### Expected behavior:

Contact form text must keep the color black.

### Current behavior:

Text color turns white in dark mode

### Reference:

Starter-sites Neve: 

-	Perfume Shop ( https://prnt.sc/xzclvq ) (https://www.loom.com/share/2fcbae6bb981448aab64c4bc72dfc9ee ) ;
-	Web Agency (https://www.loom.com/share/66df409491f24844bb4d5c224b645cd9 );
-	Fitness, in this case, even if the primary color remains the same in regular mode and in dark mode, the text is still not visible (https://prnt.sc/xzekvk ) 

Starter-sites Neve Pro:

-	Perfume Shop – the same symptoms ;
-	Web Agency – the same symptoms;
-	Fitness – the same symptoms;

Original starter site is fine.

### Technical info
* WordPress version: 5.6
* Theme version: 2.10.0

**Comment by mghenciu** [comment]
For the Fitness, Perfume Shop & Web Agency demos, I fixed the issue.
![image](https://user-images.githubusercontent.com/52494172/107963002-4a83a200-6fb0-11eb-894c-75884c118363.png)
![image](https://user-images.githubusercontent.com/52494172/107963170-7dc63100-6fb0-11eb-81f3-1261e02334e3.png)
![image](https://user-images.githubusercontent.com/52494172/107963777-42783200-6fb1-11eb-9c6d-6e7d7853d6be.png)

Something to keep in mind regarding the Global Color palettes, is that we are currently configuring all the demos to use Global Colors, so it's a work in progress task. And if you want to see the list with already configured sites, you can find it in Notion.

Also a good practice is to mention the builder/demo url in the ticket, as we have for each site different instances (up to 6), so it's easier to find it this way.

**Comment by mghenciu** [comment]
This was present on more demos, @tudor-themeisle, not only on the ones mentioned above.
I am fixing them before uploading in Templates Cloud. 

Thanks for pointing this out 🚀

**Comment by tudor-themeisle** [comment]
@mghenciu Thank you, I will keep in mind to mention the builder/demo URL in the ticket next time, sorry for that. Nice to be of help.
