### ISSUE TITLE
Activate Elementor if importing Elementor templates

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/templates-patterns-collection#53]
If you import Elementor page templates from the dashboard, it imports even when the Elementor isn't active nor it requires you to do it. Basically, it imports a blank page with a title. The modal should have a message saying or a checkbox taking the user's consent to install Elementor.

**Comment by HardeepAsrani** [comment]
I'm a bit confused about how importing works normally. Can you help with some pointers? @abaicus

**Comment by HardeepAsrani** [comment]
_bump @abaicus_

**Comment by abaicus** [comment]
@HardeepAsrani Sorry for missing this at some point.

There's a rest route that handles plugin install and activation [here](https://github.com/Codeinwp/templates-patterns-collection/blob/master/includes/Rest_Server.php#L48-L58).

This could be used to install & activate plugins. It will receive an array of `[plugin_slug => true]`  if you want to install and activate the plugin before importing. 

Let me know if you need further help implementing this.

**Comment by mghenciu** [comment]
@HardeepAsrani , it works, meaning that it does Adds & Activates Elementor/Beaver Builder.
Not sure what is the 'ethical' way to do this, as we install & activate something on client's websites without their permission + the pop-up still says this: 'This import **does not include any** plugins or theme settings.'
![Screenshot 2021-04-07 at 15 57 27](https://user-images.githubusercontent.com/52494172/113870229-4870df00-97ba-11eb-9475-1b91a8fac5db.png)

Maybe it could say that **This import includes a plugin/page-builder, but not the theme settings.**
And later we can improve on it.

**Comment by HardeepAsrani** [comment]
@mghenciu Sorry, I missed that. Thanks for catching it!
