### ISSUE TITLE
Uploading Elementor pages from Starter Sites, doesn't work

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#54]
### Description:

In the process of uploading Elementor Starters Sites to TPC, I managed to upload the main demo ([web agency](https://demosites.io/web-agency)) & generic pages, but after that I am getting an error when I try to upload a new Elementor Page.

### How to reproduce:

1. Open an Elementor demo, https://demosites.io/fitness or https://demosites.io/onboarding
2. Open any page from this demo in Edit mode
3. Try to Save the page as a Template & Upload it in Templates Cloud

### Expected behaviour:
The upload modal should work as expected

### Current behaviour:
An error appears in Console, and modal disappears (only a border is visible); see the attached screenshots

### Reference:

![image](https://user-images.githubusercontent.com/52494172/107965549-5755c500-6fb3-11eb-8951-17973515487e.png)

https://www.loom.com/share/95aec2f0e70c427ab59949eae801926f

### Technical info
* WordPress version: 5.6.1
* Theme version: 2.10.1
* Elementor v3.0.14

cc. @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@mghenciu Just one more info needed, so when exactly did it happen? After you've uploaded few templates to the cloud? Are you using post or page post-type?

**Comment by mghenciu** [comment]
It happened exactly when I tried to upload the second Starter Site, basically home page from this demo: https://demosites.io/onboarding (it's one of the oldest ones, not sure if it has something 'special' that caused it).

For the first demo (https://demosites.io/web-agency) everything went ok.

**Comment by HardeepAsrani** [comment]
I've released a fix, please check and update this issue. @mghenciu

**Comment by mghenciu** [comment]
It's working now.
Thanks!
