### ISSUE TITLE
Minor fixes/improvements for the Page Search functionality

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#60]
### Description:

**Scope**
Improve & fix the overall experience when searching/importing Pages from TPC.

**User stories:**
 
- [x] As a **User**, I want to **browse/search through pages in a easy way**, So that **I can find the right page fast.**

At the moment if an user goes to My Library or Page Templates, and searches for a keyword, this happens:

1. Going back to seeing all templates isn't very intuitive/easy. Right now if I search for a keyword, the only way to go back (see all the pages) is by refreshing the page
![Screenshot 2021-02-25 at 11 23 44](https://user-images.githubusercontent.com/52494172/109132496-92e35280-775c-11eb-857f-4aa280bd5603.png)

Maybe we could use an approach similar to Starter Sites search bar, where you have the option (X icon) to remove the search keyword, which shows all the templates
![Screenshot 2021-02-25 at 11 30 03](https://user-images.githubusercontent.com/52494172/109133984-38e38c80-775e-11eb-8fa9-29c5f8edf1bd.png)
  

2. The Search Icon is not clickable. Should be clickable as it's not clear (from the start) that it only works with Enter key or that it works/doesn't while user types.
![image](https://user-images.githubusercontent.com/52494172/109127603-48130c00-7757-11eb-9421-6ba109ad6ff9.png)

- [x] As a **User**, I want to **know if the preview is working/loading**, So that **I can see it** or just move to another one.

Right now when a user tries to preview a Elementor page, there are no clues about the page preview loading, or something else happening in background. It takes 5 seconds to see the preview on a normal connection and more than 7 sec on a slower one. If users don't have any clues about the loading state, they may just think that the preview isn't working.
A spinner or other loading visual clue can fix this. Right now the only thing visible is the loading url, on the bottom left side.
![Screenshot 2021-02-25 at 11 46 58](https://user-images.githubusercontent.com/52494172/109135832-2c603380-7760-11eb-8cf5-bdb6f9b56655.png)

- [x] As a **User**, I want to **see as many pages relevant to my search**, So that **I can find the right one** 

At the moment the search functionality doesn't return all the expected results (may be something related to keywords or if a page is part of the latest release):
for example, as you can see in the screenshoot, there are pages with title Services
![Screenshot 2021-02-25 at 12 05 38](https://user-images.githubusercontent.com/52494172/109137431-ddb39900-7761-11eb-8207-b1c0ac356a11.png)
but if I search for the **services** keyword, this are the results
![image](https://user-images.githubusercontent.com/52494172/109137533-f9b73a80-7761-11eb-91f8-2c3cd5b2adf4.png)

**Comment by HardeepAsrani** [comment]
Thank you @mghenciu - I've fixed the first two issues. The last one I added to templates cloud repository as it's more related to it: https://github.com/Codeinwp/templates-cloud/issues/20

Thanks again!

**Comment by mghenciu** [comment]
Tested all the points & everything looks good @HardeepAsrani . Thank you!

The only small thing I would change (can be done in next releases) is the Search **input field** from Page Templates & My library. Ideally it should be working like the one from Starter Sites tab, meaning that it searches while you type (to be consistent).

and add 10px padding on BB Tab, for consistency with other tabs
![Screenshot 2021-04-07 at 15 40 37](https://user-images.githubusercontent.com/52494172/113867867-b5cf4080-97b7-11eb-8145-bbbd15c9eb51.png)

**Comment by HardeepAsrani** [comment]
@mghenciu We can't do that because we make rest requests for templates, unlike starter sites which are appended at once.
