### ISSUE TITLE
Publish button gets stuck after publishing 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#61]
### Description:

On demosites.io, when saving a Gutenberg page, after I add all the details, and click Publish, the button state changes to Unpublishing. Everything looks to be working and the page is published, but the only way to see the expected button state - is to refresh the page. (see the video)

### How to reproduce:

1. Open an Gutenberg demo page, that's not in the Template Cloud
2. Save the page as template
3. All some details and click Publish
 

### Expected behaviour:
The button should change to the Unpublish state, not remain stuck in an infinite loading state
### Reference:

https://www.loom.com/share/712ae2db8f2f484a9b4bcb052f30db5e

### Technical info
WordPress version: 5.6.1
Theme Version: 2.10.1
TPC Version 1.1.4

**Comment by HardeepAsrani** [comment]
Does it still happen after few changes we made last week @mghenciu?

**Comment by HardeepAsrani** [comment]
@mghenciu It should be fixed in the Development branch. Can you check and close?

**Comment by mghenciu** [comment]
Works as expected now.

Thanks!

**Comment by selul** [comment]
no need to close it until this get released :D

**Comment by HardeepAsrani** [comment]
@selul Doesn't really matter as this is not for the user and we already use the development version on our side.
