### ISSUE TITLE
[PHP 8] Function libxml_disable_entity_loader() is deprecated error when importing a starter site

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#62]
### Description:

With PHP 8 installed, i get this error in the debug log after importing a starter site
`PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated`
### How to reproduce:

1. Install PHP 8
2. Install Neve and TPC
3. Set the WP_DEBUG_LOG to true
4. Import a starter site and check the debug log

### Reference:

[debug.log](https://github.com/Codeinwp/templates-patterns-collection/files/6090139/debug.log)  (The errors after the mentioned ones are already reported)

### Technical info
* WordPress version: 5.6.2 / 5.7
* PHP: 8
* Neve: this PR https://github.com/Codeinwp/neve/pull/2605 as it fixed other PHP 8 errors
* TPC: 1.4.2

**Comment by selul** [comment]
I've fixed this here https://github.com/Codeinwp/templates-patterns-collection/pull/69
