### ISSUE TITLE
No templates found after deleting only one template

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/templates-patterns-collection#71]
### Description:

From time to time, when i delete a template, the My library section shows `No templates found`, until i refresh the page and they are there again. 
### How to reproduce:

1. Create more templates
2. Try to delete them one by one, until this happens
3. Refresh the page to see if the templates are showing again

### Reference:

https://www.loom.com/share/383e1dbb6e6a41ebae9942dec2ee9a9c
### Technical info
* WordPress version: 5.6.2
* Neve: 2.10.2
* Neve pro: 1.4.2
* TPC:  1.1.4

**Comment by HardeepAsrani** [comment]
@irinelenache Should be fixed in https://github.com/Codeinwp/templates-patterns-collection/pull/59, can you test and close?

**Comment by irinelenache** [comment]
#59 fixes the problem 👍
