### ISSUE TITLE
Starter sites page not opening in the latest version

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#73]
### Description:

Using the latest version of the plugin causes the Starter Sites page not to load.

### How to reproduce:

1. Install and activate Neve 2.10.3
2. Install and activate Templates Patterns Collections 1.1.5
3. Try opening the Starter Sites page.

### Expected behavior:

To see the starter sites library.

### Current behavior:

The page doesn't load.

### Reference:

<img width="1914" alt="Markup 2021-03-16 at 20 42 42" src="https://user-images.githubusercontent.com/26867648/111363026-322ea200-8698-11eb-82b7-3f5c4730a57c.png">

### Technical info
* WordPress version: 5.7
* Theme version: 2.10.3
* Plugin version: 1.1.5

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/1455643689/271138/

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani just making sure you're aware of this, thanks!

**Comment by HardeepAsrani** [comment]
Should be fixed @stefan-cotitosu - can you check and close this issue? Thank you!

**Comment by stefan-cotitosu** [comment]
It works, thanks.
