### ISSUE TITLE
Improve user flows for Template CRUD features   

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#78]
### Description:

A few suggestions regarding the CRUD features for templates in TPC:
@HardeepAsrani 

**Gutenberg:**

- [ ] As a pro-user, I want to know if the current gb page was Saved/published before so that I know if I need to save it now or not.
Basically if I save a gb page in TPC, and later edit that page, how do I know if the page is already saved in TPC? 
This is how a gb page Saved in TPC , looks like in edit mode (no clue that the page is already in TPC or not):
![image](https://user-images.githubusercontent.com/52494172/113847267-f91db500-979f-11eb-9f43-d3e22a4d3e16.png)

**Elementor & Beaver Builder**
- [ ] Same user story as the one above. This is how a Elementor page, saved in TPC looks in edit mode
![image](https://user-images.githubusercontent.com/52494172/113849961-a5609b00-97a2-11eb-830f-52a36454cda0.png)
how do I know that the page is already saved in TPC?

**For all Builders**
- [ ] As an agency, I want to easily add a page in TPC without entering in Edit mode, so I can save time.
Basically adding the option to save a page in wp-admin:
![image](https://user-images.githubusercontent.com/52494172/113851737-7b0fdd00-97a4-11eb-9381-0ab73cf46a6d.png)

- [ ] | _low-priority_ | As an agency, I want to easily add multiple pages in TPC, so I don't enter in Edit mode for each page I want to publish.
One solution may be Bulk actions for TPC, but I am not sure how easy is to implement something like this.
![image](https://user-images.githubusercontent.com/52494172/113851462-3421e780-97a4-11eb-9c13-39e7bade0441.png)

- [ ]  | _low-priority_ | As a Admin (me), I want to know why a page I deleted from TPC, still has the Unpublish button active, so I don't get confused on what should I do next (unpublish, republish, did the delete worked?).
Theoretically, if I delete a Template from TPC, when I edit the same Template -> I should start from scratch or at least have the visual feedback in UI that the page needs to be Republished (as it was deleted before)

P.S. fell free to convert to-do items in separate issues, I added them all here as suggestions, so take it with a grain of salt.

**Comment by HardeepAsrani** [comment]
@mghenciu I've fixed the first issue (need to commit but the laptop is being repaired, so will commit in 3 days).

For the publish/bulk publish, the issue comes that we can't get the page-builder-specific data from the dashboard without having the page open, especially with Elementor in which we get the data using JavaScript functions available in its API, so not sure if it only works with certain page builders. What do you think?

**Comment by mghenciu** [comment]
> @mghenciu I've fixed the first issue (need to commit but the laptop is being repaired, so will commit in 3 days).
> 
> For the publish/bulk publish, the issue comes that we can't get the page-builder-specific data from the dashboard without having the page open, especially with Elementor in which we get the data using JavaScript functions available in its API, so not sure if it only works with certain page builders. What do you think?

Thanks for the update, @HardeepAsrani .
I understand the technical limitations.
What do you think if we at least add a Clone/Duplicate page button in the page editor? here for example
![Screenshot 2021-09-02 at 08 56 40](https://user-images.githubusercontent.com/52494172/131789769-35d47568-8af4-4e5c-b34c-65858694336d.png)

which will create a Duplicate of the same page, with the same settings, and increment the name.


The pain point I was trying to address with bulk/dashboard publish, is having to repeat the same configuration steps each time. For example we have 10 Home generic pages, and for each of them I had to repeat the same process of Create new page, add page settings, open it in editor, publish to cloud. Which is not very efficient at a large scale. Of course, probably most agencies have a Duplicate Page plugin, but this was the idea behind.

**Comment by HardeepAsrani** [comment]
>  What do you think if we at least add a Clone/Duplicate page button in the page editor?

@mghenciu We do have a route to duplicate templates but that is made only if someone wants to duplicate an existing template, which won't duplicate the page itself as that will be a long process that not many will use as not everyone will be storing everything to the cloud.

The easiest way is just to use a Duplicate Page plugin and save it back to the cloud after one has made the changes they want.
