### ISSUE TITLE
Product categories remapping fails

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/templates-patterns-collection#81]
### Description:
If we use the product category block, sometimes it fails as it can't remap the id to the proper category.

### How to reproduce:

1. Import the Digital Store expert demo;
2. The import sometimes yields unexpected results as `product_cat` id's are not always the same

### Reference:
![image](https://user-images.githubusercontent.com/15010186/116395419-c4e06600-a82c-11eb-9b96-a14a71ce93a2.png)

**Comment by HardeepAsrani** [comment]
We can't really do much about it. We can write some function to map ID to slug, and then remap it but it will have to be done for each block. It will be too much work doing it for each block, as there will be many, and even then there's no guarantee that category slug will be same. What do you think @selul?

**Comment by selul** [comment]
We can think of some solutions, right now it makes the importing unusable in this fashion.

**Comment by HardeepAsrani** [comment]
I really don't know what one can do about it when we have no way to control what category other people might have. We should be using blocks without category/tags, like top 5 products, sale products, and such.

Let me know if someone can think of a good solution.

**Comment by selul** [comment]
We can review a bit the importing and think of some mapping mechanism where we export on the demosites end the entities to map as placeholders and replace them on import with actual ones. 

@preda-bogdan will leave this on your plate when the time will come.

**Comment by preda-bogdan** [comment]
I've update both repositories `template-patterns-collection` and `demo-data-exporter`
The exporter should replace those categories with `replace_cat_%d` on export for Gutenberg blocks
The template pattern will parse these placeholders if present and remap them to the imported categories.

Let me know if this is the desired approach. I've also added PhpUnit for this specific case and improved on the existing tests to check for all parsed data.
