### ISSUE TITLE
Sharing & Online preview of Templates

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/templates-patterns-collection#85]
We need to add some mechanism to allow users to share the blocks & online preview of templates, at least for Gutenberg one.

**Comment by HardeepAsrani** [comment]
Thinking about this workflow. Here's what I think we can approach, keeping it flexible for future changes:

We will have a 'visibility' field to the API. By default all will be private and hence not shared but a person can click on "Share with a friend" and that will switch the visibility to "public."

We can approach this with either two status or three:

- Public (Anyone with ID)
- Private (No one)
- Shared (Anyone one with ID + API key)

Either we can have only Public/Private or we can also have a third option of allowing sharing with people who have the ID + key. I suppose we can generate the key from their license key with some random hash.

And if they want to share the whole collection, they can turn it on too and other people can add it to their library.

What do you think about how to approach? @selul

**Comment by HardeepAsrani** [comment]
For Preview, the proper thum.io URL will be: will be: `https://image.thum.io/get/auth/APIKEYHERE/png/noanimate/fullpage/viewportWidth/1400/width/800/crop/1750/https://demosites.io/starter-sites-staging/home-7/?tpcpreview=yes`

**Comment by selul** [comment]
@HardeepAsrani for thum.io we will use it just to get the image no and save it to our bucket? I wouldn't send the thum URLs back to users. 

> What do you think about how to approach? @selul 

I think is solid, one thing that concerns is the online preview, how will it work? i mean not the screenshot, the preview of the template.

**Comment by HardeepAsrani** [comment]
> @HardeepAsrani for thum.io we will use it just to get the image no and save it to our bucket? I wouldn't send the thum URLs back to users.

Yea, I just added the URL in the Github thread to safe keeping, so I can come back to it for what's the perfect URL.

> I think is solid, one thing that concerns is the online preview, how will it work? i mean not the screenshot, the preview of the template.

I'm talking of approaching it post-screenshot. I've few ideas and we can see which can work better. Screenshots > Sharing > Preview, as people can already preview their own templates so preview is only useful after the sharing option.
