### ISSUE TITLE
Fatal error: conflict with Beaver Builder

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/templates-patterns-collection#92]
### Description:

There are some warnings and a fatal error when the latest version of the plugin is installed and active alongside Beaver Builder.

### How to reproduce:

1. Install and activate Neve
2. Install and activate Templates Patterns Collection
3. Install and activate Beaver Builder

<img width="784" alt="Screenshot on 2021-05-17 at 12-53-20" src="https://user-images.githubusercontent.com/26867648/118469960-e5eef500-b70e-11eb-855e-869a4f97a440.png">

### Reference:

I was able to replicate it on a local instance, tastewp, and jurassic.ninja.

URL: https://clean-tahr.jurassic.ninja
username: demo
pass: DvwRKo1glOox

### Technical info
* WordPress version: 5.7.2
* Theme version: 1.1.11
* Beaver Builder: 2.4.2.2

**Comment by selul** [comment]
This is fixed in https://github.com/Codeinwp/templates-patterns-collection/releases/tag/v1.1.12
