### ISSUE TITLE
Elementor Custom Image size, is not applied after import

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#99]
### Description:

In Elementor users have the option to use a custom size for an Image.
The issue comes when you import pages with such images, because the Custom Image size is not applied.
Left-side is origin (where the Icons use Custom size 80x80), and on the right-side is the imported version.
![image](https://user-images.githubusercontent.com/52494172/120814407-83dc1f80-c557-11eb-9289-50f0258b87fc.png)

And after import, the Custom values are there, but they are not applied:
![Screenshot 2021-06-03 at 13 45 01](https://user-images.githubusercontent.com/52494172/120815352-68254900-c558-11eb-8099-b7318a302c00.png)

Or maybe it's related to the fact that the Images are not imported when you import a Generic Page (so it doesn't have on what to apply the images)
### How to reproduce:

1. Create a Elementor page with a Image using Custom Size
2. Save it in TPC
3. Import the page on another site
4. Notice the Image size

### Technical info
* WordPress 5.7.2 
* Theme version: 2.11.6
* Elementor v3.2.4
* TPC Version 1.1.13

**Comment by HardeepAsrani** [comment]
> Or maybe it's related to the fact that the Images are not imported when you import a Generic Page (so it doesn't have on what to apply the images)

Might be that. I'll check it out, thank you!

**Comment by HardeepAsrani** [comment]
I tried it yesterday and it worked properly for me. Of course, I tried with new templates so make it easier to reproduce. Is it happening for you with new templates? @mghenciu

**Comment by mghenciu** [comment]
I did some testing now, and it looks to be a NAD (not a defect), or most probably this is how Elementor works.
The issue looks to be caused by the fact that when you import a (generic) page, the assets are not imported, so as mentioned above, Elementor won't know on what image to apply the Custom Size.

I tried with the [Doctor demo](https://demosites.io/doctor/doctor-about/), importing only the About page, and Custom Image size it's not applied. But if I import the full site (which means the assets are imported), the Custom size it's applied.

I don't think we can do something about it, I'll just add a note in Design Docs, to not use Custom Image size.
And we can close this. @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@mghenciu Does it happen when you import from within Elementor using Templates Cloud modal? I suppose that shouldn't happen and it should import the images too.

**Comment by mghenciu** [comment]
@HardeepAsrani If you mean importing from here 
![image](https://user-images.githubusercontent.com/52494172/121137682-94ceae80-c83f-11eb-8bca-80120ef043c9.png) on an Elementor page, the Images are not imported, or at least not on my end. So probably the same thing happens, the Custom Image it's there, but it doesn't have the asset.

Here I imported Services 4 page, using the TPC modal:
![Screenshot 2021-06-08 at 09 53 13](https://user-images.githubusercontent.com/52494172/121137788-b5970400-c83f-11eb-82d9-21aed09c0c3e.png)

**Comment by HardeepAsrani** [comment]
Oh yea, my bad, we don't import the images but server thru the cloud. I'll take a deeper look once I'm finished with current tasks.

**Comment by HardeepAsrani** [comment]
@selul Here we can't do much with the sizing option as our images aren't stored locally. Elementor allows users to use either predefined WordPress image sizes (cropped image files) or the custom option. The custom option also generates a new image crop.

So yea, it can only be done by storing images locally. What do you think?

**Comment by HardeepAsrani** [comment]
Closing this as this is a common issue with how Elementor works as it doesn't provide option to use remote images. The support is only for native WP images. The only solution will be to upload all the images to WP. Another non-ideal way would've been to use this filter to add inline sizes: https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/includes/controls/groups/image-size.php#L137

So yea, closing this for now. We can revisit this when Elementor adds support for remote images or some other solution comes up.

**Comment by HardeepAsrani** [comment]
Thanks for the report @mghenciu, by the way. Good find!
